import Vue from 'vue'

const newBadgeSvg = () => import('./new-badge-svg.vue')
const usernameSvg = () => import('./username-svg.vue')
const mrnSvg = () => import('./mrn-svg.vue')
const passwordSvg = () => import('./password-svg.vue')
const locationSvg = () => import('./location-svg.vue')
const calendarSvg = () => import('./calendar-svg.vue')
const otpSvg = () => import('./otp-svg.vue')
const bellFillSvg = () => import('./bell-fill-svg.vue')
const userSvg = () => import('./user-svg.vue')
const userFillSvg = () => import('./user-fill-svg.vue')
const lockSvg = () => import('./lock-svg.vue')
const changeCommentSvg = () => import('./change-comment-svg.vue')
const reminderSvg = () => import('./reminder-svg.vue')
const atom = () => import('./modules/atom')
const calendar = () => import('./modules/calendar')
const callHelp = () => import('./modules/call-help')
const doctorLaptop = () => import('./modules/doctor-laptop')
const doctor = () => import('./modules/doctor')
const family = () => import('./modules/family')
const healthShield = () => import('./modules/health-shield')
const briefcase = () => import('./modules/briefcase')
const heartCheckup = () => import('./modules/heart-checkup')
const lab = () => import('./modules/lab')
const laptop = () => import('./modules/laptop')
const medicalJar = () => import('./modules/medical-jar')
const promotions = () => import('./modules/promotions')
const symptom = () => import('./modules/symptom')
const timeline = () => import('./modules/timeline')
const userReport = () => import('./modules/user-report')
const userTag = () => import('./modules/user-tag')
const dashboardSvg = () => import('./modules/dashboard-svg.vue')
const heartReport = () => import('./modules/heart-report-svg.vue')
const calendarFill = () => import('./modules/calendar-fill.vue')
const hospital = () => import('./modules/hospital.vue')
const shield = () => import('./modules/shield.vue')
const clipboard = () => import('./modules/clipboard.vue')
const walletSvg = () => import('./payment-method/wallet-svg.vue')
const appleSvg = () => import('./payment-method/apple-svg.vue')
const cashSvg = () => import('./payment-method/cash-svg.vue')
const insuranceSvg = () => import('./payment-method/insurance-svg.vue')
const labBgSvg = () => import('./lab-bg-svg.vue')
const bellBgSvg = () => import('./bell-bg-svg.vue')
const shieldBgSvg = () => import('./shield-bg-svg.vue')
const pillBgSvg = () => import('./pill-bg-svg.vue')
const atomFillSvg = () => import('./atom-fill-svg.vue')
const briefcaseFillSvg = () => import('./briefcase-fill-svg.vue')
const pillFillSvg = () => import('./pill-fill-svg.vue')
const familyFillSvg = () => import('./family-fill.vue')

Vue.component('new-badge-svg', newBadgeSvg)
Vue.component('username-svg', usernameSvg)
Vue.component('mrn-svg', mrnSvg)
Vue.component('password-svg', passwordSvg)
Vue.component('location-svg', locationSvg)
Vue.component('calendar-svg', calendarSvg)
Vue.component('otp-svg', otpSvg)
Vue.component('bell-fill-svg', bellFillSvg)
Vue.component('user-svg', userSvg)
Vue.component('user-fill-svg', userFillSvg)
Vue.component('lock-svg', lockSvg)
Vue.component('change-comment-svg', changeCommentSvg)
Vue.component('reminder-svg', reminderSvg)
Vue.component('dashboard-svg', dashboardSvg)
Vue.component('heart-report-svg', heartReport)
Vue.component('atom-svg', atom)
Vue.component('calendar-svg', calendar)
Vue.component('call-help-svg', callHelp)
Vue.component('doctor-laptop-svg', doctorLaptop)
Vue.component('doctor-svg', doctor)
Vue.component('family-svg', family)
Vue.component('health-shield-svg', healthShield)
Vue.component('briefcase-svg', briefcase)
Vue.component('heart-checkup-svg', heartCheckup)
Vue.component('lab-svg', lab)
Vue.component('laptop-svg', laptop)
Vue.component('medical-jar-svg', medicalJar)
Vue.component('promotions-svg', promotions)
Vue.component('symptom-svg', symptom)
Vue.component('timeline-svg', timeline)
Vue.component('user-report-svg', userReport)
Vue.component('user-tag-svg', userTag)
Vue.component('calendar-fill-svg', calendarFill)
Vue.component('hospital-svg', hospital)
Vue.component('shield-svg', shield)
Vue.component('clipboard-svg', clipboard)
Vue.component('wallet-svg', walletSvg)
Vue.component('apple-svg', appleSvg)
Vue.component('cash-svg', cashSvg)
Vue.component('insurance-svg', insuranceSvg)
Vue.component('lab-bg-svg', labBgSvg)
Vue.component('bell-bg-svg', bellBgSvg)
Vue.component('shield-bg-svg', shieldBgSvg)
Vue.component('pill-bg-svg', pillBgSvg)
Vue.component('atom-fill-svg', atomFillSvg)
Vue.component('briefcase-fill-svg', briefcaseFillSvg)
Vue.component('pill-fill-svg', pillFillSvg)
Vue.component('family-fill-svg', familyFillSvg)